---
- name: apache is installed and started
  user: root
  hosts: web
  become: yes

  tasks:
  - name: install httpd package 
    yum:
      name: httpd
      state: present

  - name: start apache 
    service:
      name: httpd
      state: started
